name: Build ImmortalWrt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
          gettext git java-propose-classpath jq libelf-dev libncurses5-dev \
          libncursesw5-dev libssl-dev python3 python3-pip python3-ply \
          python3-pyelftools unzip wget xsltproc zlib1g-dev

      - name: Clone ImmortalWrt source
        run: |
          git clone https://github.com/immortalwrt/immortalwrt.git
          cd immortalwrt
          git checkout openwrt-23.05

      - name: Copy custom .config
        run: |
          cp .config immortalwrt/.config

      - name: Update and install feeds
        working-directory: immortalwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure build
        working-directory: immortalwrt
        run: |
          make defconfig

      - name: Download dependencies
        working-directory: immortalwrt
        run: |
          make download -j$(nproc)

      - name: Build ImmortalWrt
        working-directory: immortalwrt
        run: |
          make -j$(nproc) V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-firmware
          path: immortalwrt/bin/targets/*/*/*.bin
